const pie_data={
    "saakashvili": {
        "გირჩი": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 24,
                "viewCount": 93399,
                "favoriteCount": 0,
                "shareCount": 527,
                "loveCount": 96,
                "wowCount": 36,
                "hahaCount": 389,
                "sadCount": 22,
                "angryCount": 150,
                "thankfulCount": 0,
                "careCount": 11,
                "likeCount": 6944,
                "commentCount": 1763
            }
        },
        "ერი": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            }
        },
        "ქართული ოცნება": {
            "Pole A": {
                "count": 3,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 32,
                "loveCount": 34,
                "wowCount": 5,
                "hahaCount": 85,
                "sadCount": 1,
                "angryCount": 93,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 1109,
                "commentCount": 164
            },
            "Pole B": {
                "count": 18,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1137,
                "loveCount": 519,
                "wowCount": 35,
                "hahaCount": 746,
                "sadCount": 71,
                "angryCount": 1973,
                "thankfulCount": 0,
                "careCount": 26,
                "likeCount": 11298,
                "commentCount": 3397
            },
            "Neutral": {
                "count": 20,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1223,
                "loveCount": 337,
                "wowCount": 28,
                "hahaCount": 261,
                "sadCount": 53,
                "angryCount": 541,
                "thankfulCount": 0,
                "careCount": 12,
                "likeCount": 10565,
                "commentCount": 1896
            }
        },
        "საქართველოსთვის": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 3,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 177,
                "loveCount": 104,
                "wowCount": 13,
                "hahaCount": 140,
                "sadCount": 6,
                "angryCount": 105,
                "thankfulCount": 0,
                "careCount": 6,
                "likeCount": 1666,
                "commentCount": 327
            }
        },
        "ერთიანი ნაციონალური მოძრაობა": {
            "Pole A": {
                "count": 171,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 10014,
                "loveCount": 12361,
                "wowCount": 516,
                "hahaCount": 16966,
                "sadCount": 1366,
                "angryCount": 2171,
                "thankfulCount": 0,
                "careCount": 881,
                "likeCount": 82440,
                "commentCount": 27483
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 85,
                "loveCount": 3,
                "wowCount": 13,
                "hahaCount": 48,
                "sadCount": 0,
                "angryCount": 29,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 85,
                "commentCount": 97
            },
            "Neutral": {
                "count": 67,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 4252,
                "loveCount": 6060,
                "wowCount": 772,
                "hahaCount": 5402,
                "sadCount": 3843,
                "angryCount": 1036,
                "thankfulCount": 0,
                "careCount": 488,
                "likeCount": 33374,
                "commentCount": 11743
            }
        },
        "ხალხისთვის": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            }
        },
        "სტრატეგია აღმაშენებელი": {
            "Pole A": {
                "count": 12,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 805,
                "loveCount": 378,
                "wowCount": 52,
                "hahaCount": 1402,
                "sadCount": 946,
                "angryCount": 292,
                "thankfulCount": 0,
                "careCount": 65,
                "likeCount": 5362,
                "commentCount": 3136
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 5,
                "loveCount": 1,
                "wowCount": 0,
                "hahaCount": 2,
                "sadCount": 0,
                "angryCount": 1,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 11,
                "commentCount": 1
            },
            "Neutral": {
                "count": 6,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 141,
                "loveCount": 141,
                "wowCount": 12,
                "hahaCount": 299,
                "sadCount": 6,
                "angryCount": 20,
                "thankfulCount": 0,
                "careCount": 8,
                "likeCount": 855,
                "commentCount": 250
            }
        },
        "მოქალაქეები": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 3,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1,
                "loveCount": 2,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 1,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 42,
                "commentCount": 4
            }
        },
        "კონსერვატიული მოძრაობა": {
            "Pole A": {
                "count": 4,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 288,
                "loveCount": 1,
                "wowCount": 3,
                "hahaCount": 0,
                "sadCount": 112,
                "angryCount": 46,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 162,
                "commentCount": 102
            },
            "Pole B": {
                "count": 6,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 5,
                "commentCount": 1
            },
            "Neutral": {
                "count": 155,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 135,
                "loveCount": 37,
                "wowCount": 0,
                "hahaCount": 10,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 685,
                "commentCount": 61
            }
        },
        "ხალხის ძალა": {
            "Pole A": {
                "count": 15,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 458,
                "loveCount": 243,
                "wowCount": 10,
                "hahaCount": 192,
                "sadCount": 23,
                "angryCount": 389,
                "thankfulCount": 0,
                "careCount": 13,
                "likeCount": 5019,
                "commentCount": 1276
            },
            "Pole B": {
                "count": 59,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1272,
                "loveCount": 561,
                "wowCount": 42,
                "hahaCount": 161,
                "sadCount": 38,
                "angryCount": 90,
                "thankfulCount": 0,
                "careCount": 18,
                "likeCount": 10849,
                "commentCount": 1531
            },
            "Neutral": {
                "count": 105,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 2589,
                "loveCount": 718,
                "wowCount": 82,
                "hahaCount": 350,
                "sadCount": 46,
                "angryCount": 274,
                "thankfulCount": 0,
                "careCount": 33,
                "likeCount": 18984,
                "commentCount": 2623
            }
        },
        "ევროპული საქართველო - მოძრაობა თავისუფლებისთვის": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            }
        },
        "პატრიოტთა ალიანსი": {
            "Pole A": {
                "count": 4,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 29,
                "loveCount": 17,
                "wowCount": 0,
                "hahaCount": 3,
                "sadCount": 1,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 149,
                "commentCount": 22
            },
            "Pole B": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 10,
                "loveCount": 2,
                "wowCount": 1,
                "hahaCount": 3,
                "sadCount": 0,
                "angryCount": 9,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 55,
                "commentCount": 22
            },
            "Neutral": {
                "count": 5,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 26,
                "loveCount": 6,
                "wowCount": 1,
                "hahaCount": 12,
                "sadCount": 0,
                "angryCount": 11,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 169,
                "commentCount": 37
            }
        },
        "ლელო": {
            "Pole A": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 7,
                "commentCount": 0
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 4,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 55,
                "commentCount": 5
            },
            "Neutral": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 4,
                "loveCount": 6,
                "wowCount": 0,
                "hahaCount": 1,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 50,
                "commentCount": 2
            }
        },
        "გირჩი - მეტი თავისუფლება": {
            "Pole A": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 614,
                "loveCount": 123,
                "wowCount": 1,
                "hahaCount": 7,
                "sadCount": 11,
                "angryCount": 5,
                "thankfulCount": 0,
                "careCount": 7,
                "likeCount": 3805,
                "commentCount": 247
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 614,
                "loveCount": 2,
                "wowCount": 37,
                "hahaCount": 23,
                "sadCount": 56,
                "angryCount": 4123,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 131,
                "commentCount": 637
            },
            "Neutral": {
                "count": 4,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 23,
                "loveCount": 21,
                "wowCount": 3,
                "hahaCount": 3,
                "sadCount": 6,
                "angryCount": 2,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 272,
                "commentCount": 36
            }
        },
        "ლეიბორისტული პარტია": {
            "Pole A": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 8,
                "loveCount": 19,
                "wowCount": 2,
                "hahaCount": 37,
                "sadCount": 0,
                "angryCount": 6,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 370,
                "commentCount": 79
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 38,
                "loveCount": 15,
                "wowCount": 9,
                "hahaCount": 14,
                "sadCount": 8,
                "angryCount": 12,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 847,
                "commentCount": 164
            }
        },
        "დროა": {
            "Pole A": {
                "count": 3,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 18,
                "loveCount": 27,
                "wowCount": 1,
                "hahaCount": 11,
                "sadCount": 0,
                "angryCount": 1,
                "thankfulCount": 0,
                "careCount": 3,
                "likeCount": 244,
                "commentCount": 26
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            }
        }
    },
    "russ_vv": {
        "გირჩი": {
            "Pole A": {
                "count": 5,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 10,
                "loveCount": 5,
                "wowCount": 3,
                "hahaCount": 13,
                "sadCount": 0,
                "angryCount": 4,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 250,
                "commentCount": 54
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 89,
                "viewCount": 240776,
                "favoriteCount": 0,
                "shareCount": 2137,
                "loveCount": 1081,
                "wowCount": 57,
                "hahaCount": 734,
                "sadCount": 88,
                "angryCount": 925,
                "thankfulCount": 0,
                "careCount": 44,
                "likeCount": 18093,
                "commentCount": 4221
            }
        },
        "ერი": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 83,
                "viewCount": 28889,
                "favoriteCount": 0,
                "shareCount": 388,
                "loveCount": 272,
                "wowCount": 3,
                "hahaCount": 2,
                "sadCount": 2,
                "angryCount": 10,
                "thankfulCount": 0,
                "careCount": 10,
                "likeCount": 2869,
                "commentCount": 183
            }
        },
        "ქართული ოცნება": {
            "Pole A": {
                "count": 18,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 261,
                "loveCount": 65,
                "wowCount": 1,
                "hahaCount": 61,
                "sadCount": 4,
                "angryCount": 31,
                "thankfulCount": 0,
                "careCount": 6,
                "likeCount": 1379,
                "commentCount": 165
            },
            "Pole B": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 420,
                "loveCount": 15,
                "wowCount": 0,
                "hahaCount": 9,
                "sadCount": 3,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 1356,
                "commentCount": 147
            },
            "Neutral": {
                "count": 474,
                "viewCount": 834,
                "favoriteCount": 0,
                "shareCount": 14716,
                "loveCount": 16523,
                "wowCount": 450,
                "hahaCount": 12374,
                "sadCount": 1062,
                "angryCount": 12056,
                "thankfulCount": 0,
                "careCount": 724,
                "likeCount": 205008,
                "commentCount": 38444
            }
        },
        "საქართველოსთვის": {
            "Pole A": {
                "count": 22,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 2673,
                "loveCount": 2779,
                "wowCount": 48,
                "hahaCount": 856,
                "sadCount": 22,
                "angryCount": 259,
                "thankfulCount": 0,
                "careCount": 114,
                "likeCount": 21213,
                "commentCount": 2139
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 7,
                "loveCount": 2,
                "wowCount": 0,
                "hahaCount": 2,
                "sadCount": 1,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 197,
                "commentCount": 18
            },
            "Neutral": {
                "count": 82,
                "viewCount": 7,
                "favoriteCount": 0,
                "shareCount": 1772,
                "loveCount": 2452,
                "wowCount": 75,
                "hahaCount": 1141,
                "sadCount": 241,
                "angryCount": 507,
                "thankfulCount": 0,
                "careCount": 124,
                "likeCount": 21929,
                "commentCount": 2038
            }
        },
        "ერთიანი ნაციონალური მოძრაობა": {
            "Pole A": {
                "count": 74,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 5565,
                "loveCount": 7692,
                "wowCount": 159,
                "hahaCount": 3268,
                "sadCount": 276,
                "angryCount": 1066,
                "thankfulCount": 0,
                "careCount": 527,
                "likeCount": 50923,
                "commentCount": 13347
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 321,
                "viewCount": 1485,
                "favoriteCount": 0,
                "shareCount": 23892,
                "loveCount": 36078,
                "wowCount": 1804,
                "hahaCount": 23667,
                "sadCount": 12598,
                "angryCount": 4951,
                "thankfulCount": 0,
                "careCount": 2685,
                "likeCount": 222215,
                "commentCount": 66924
            }
        },
        "ხალხისთვის": {
            "Pole A": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 116,
                "loveCount": 10,
                "wowCount": 17,
                "hahaCount": 4,
                "sadCount": 266,
                "angryCount": 80,
                "thankfulCount": 0,
                "careCount": 6,
                "likeCount": 1370,
                "commentCount": 153
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 29,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1810,
                "loveCount": 2950,
                "wowCount": 206,
                "hahaCount": 680,
                "sadCount": 329,
                "angryCount": 894,
                "thankfulCount": 0,
                "careCount": 162,
                "likeCount": 24094,
                "commentCount": 3599
            }
        },
        "სტრატეგია აღმაშენებელი": {
            "Pole A": {
                "count": 48,
                "viewCount": 23,
                "favoriteCount": 0,
                "shareCount": 2371,
                "loveCount": 1249,
                "wowCount": 335,
                "hahaCount": 2950,
                "sadCount": 350,
                "angryCount": 2627,
                "thankfulCount": 0,
                "careCount": 130,
                "likeCount": 19019,
                "commentCount": 6965
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 5,
                "loveCount": 1,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 12,
                "commentCount": 0
            },
            "Neutral": {
                "count": 272,
                "viewCount": 84,
                "favoriteCount": 0,
                "shareCount": 16278,
                "loveCount": 23548,
                "wowCount": 630,
                "hahaCount": 9696,
                "sadCount": 6621,
                "angryCount": 4083,
                "thankfulCount": 0,
                "careCount": 2358,
                "likeCount": 199592,
                "commentCount": 37956
            }
        },
        "მოქალაქეები": {
            "Pole A": {
                "count": 4,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 27,
                "loveCount": 49,
                "wowCount": 13,
                "hahaCount": 115,
                "sadCount": 5,
                "angryCount": 18,
                "thankfulCount": 0,
                "careCount": 5,
                "likeCount": 1495,
                "commentCount": 545
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 59,
                "viewCount": 34,
                "favoriteCount": 0,
                "shareCount": 2987,
                "loveCount": 2189,
                "wowCount": 83,
                "hahaCount": 390,
                "sadCount": 111,
                "angryCount": 254,
                "thankfulCount": 0,
                "careCount": 108,
                "likeCount": 32336,
                "commentCount": 4283
            }
        },
        "კონსერვატიული მოძრაობა": {
            "Pole A": {
                "count": 14,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 2748,
                "loveCount": 68,
                "wowCount": 61,
                "hahaCount": 81,
                "sadCount": 56,
                "angryCount": 281,
                "thankfulCount": 0,
                "careCount": 9,
                "likeCount": 3473,
                "commentCount": 1226
            },
            "Pole B": {
                "count": 9,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 221,
                "loveCount": 86,
                "wowCount": 1,
                "hahaCount": 13,
                "sadCount": 2,
                "angryCount": 6,
                "thankfulCount": 0,
                "careCount": 4,
                "likeCount": 1347,
                "commentCount": 175
            },
            "Neutral": {
                "count": 822,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 26792,
                "loveCount": 3501,
                "wowCount": 1112,
                "hahaCount": 6095,
                "sadCount": 1040,
                "angryCount": 14313,
                "thankfulCount": 0,
                "careCount": 301,
                "likeCount": 66295,
                "commentCount": 18155
            }
        },
        "ხალხის ძალა": {
            "Pole A": {
                "count": 24,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 742,
                "loveCount": 168,
                "wowCount": 19,
                "hahaCount": 163,
                "sadCount": 24,
                "angryCount": 130,
                "thankfulCount": 0,
                "careCount": 7,
                "likeCount": 6925,
                "commentCount": 1251
            },
            "Pole B": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 10,
                "loveCount": 1,
                "wowCount": 0,
                "hahaCount": 3,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 92,
                "commentCount": 0
            },
            "Neutral": {
                "count": 369,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 7928,
                "loveCount": 3533,
                "wowCount": 317,
                "hahaCount": 2872,
                "sadCount": 211,
                "angryCount": 2396,
                "thankfulCount": 0,
                "careCount": 153,
                "likeCount": 73119,
                "commentCount": 11210
            }
        },
        "ევროპული საქართველო - მოძრაობა თავისუფლებისთვის": {
            "Pole A": {
                "count": 8,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 247,
                "loveCount": 155,
                "wowCount": 10,
                "hahaCount": 77,
                "sadCount": 2,
                "angryCount": 74,
                "thankfulCount": 0,
                "careCount": 11,
                "likeCount": 2519,
                "commentCount": 615
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 35,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 637,
                "loveCount": 1397,
                "wowCount": 21,
                "hahaCount": 617,
                "sadCount": 125,
                "angryCount": 323,
                "thankfulCount": 0,
                "careCount": 69,
                "likeCount": 11191,
                "commentCount": 2120
            }
        },
        "პატრიოტთა ალიანსი": {
            "Pole A": {
                "count": 4,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 101,
                "loveCount": 11,
                "wowCount": 4,
                "hahaCount": 29,
                "sadCount": 2,
                "angryCount": 9,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 376,
                "commentCount": 95
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 31,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 155,
                "loveCount": 73,
                "wowCount": 4,
                "hahaCount": 66,
                "sadCount": 2,
                "angryCount": 68,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 1462,
                "commentCount": 223
            }
        },
        "ლელო": {
            "Pole A": {
                "count": 17,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 262,
                "loveCount": 199,
                "wowCount": 7,
                "hahaCount": 341,
                "sadCount": 17,
                "angryCount": 151,
                "thankfulCount": 0,
                "careCount": 20,
                "likeCount": 3784,
                "commentCount": 639
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 149,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 4309,
                "loveCount": 6671,
                "wowCount": 125,
                "hahaCount": 2530,
                "sadCount": 1591,
                "angryCount": 893,
                "thankfulCount": 0,
                "careCount": 456,
                "likeCount": 58826,
                "commentCount": 6013
            }
        },
        "გირჩი - მეტი თავისუფლება": {
            "Pole A": {
                "count": 18,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 309,
                "loveCount": 161,
                "wowCount": 5,
                "hahaCount": 82,
                "sadCount": 6,
                "angryCount": 31,
                "thankfulCount": 0,
                "careCount": 14,
                "likeCount": 3402,
                "commentCount": 299
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 31,
                "loveCount": 103,
                "wowCount": 0,
                "hahaCount": 3,
                "sadCount": 0,
                "angryCount": 1,
                "thankfulCount": 0,
                "careCount": 5,
                "likeCount": 674,
                "commentCount": 25
            },
            "Neutral": {
                "count": 117,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 6180,
                "loveCount": 9750,
                "wowCount": 99,
                "hahaCount": 1179,
                "sadCount": 442,
                "angryCount": 5318,
                "thankfulCount": 0,
                "careCount": 389,
                "likeCount": 58643,
                "commentCount": 6467
            }
        },
        "ლეიბორისტული პარტია": {
            "Pole A": {
                "count": 8,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 149,
                "loveCount": 95,
                "wowCount": 8,
                "hahaCount": 39,
                "sadCount": 48,
                "angryCount": 19,
                "thankfulCount": 0,
                "careCount": 6,
                "likeCount": 3508,
                "commentCount": 340
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 22,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1190,
                "loveCount": 305,
                "wowCount": 113,
                "hahaCount": 615,
                "sadCount": 279,
                "angryCount": 123,
                "thankfulCount": 0,
                "careCount": 26,
                "likeCount": 8061,
                "commentCount": 1340
            }
        },
        "დროა": {
            "Pole A": {
                "count": 7,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 30,
                "loveCount": 49,
                "wowCount": 1,
                "hahaCount": 10,
                "sadCount": 1,
                "angryCount": 7,
                "thankfulCount": 0,
                "careCount": 13,
                "likeCount": 536,
                "commentCount": 39
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 49,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1549,
                "loveCount": 2784,
                "wowCount": 38,
                "hahaCount": 514,
                "sadCount": 40,
                "angryCount": 295,
                "thankfulCount": 0,
                "careCount": 182,
                "likeCount": 20545,
                "commentCount": 2620
            }
        }
    },
    "olig_vv": {
        "გირჩი": {
            "Pole A": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 19,
                "loveCount": 28,
                "wowCount": 0,
                "hahaCount": 6,
                "sadCount": 0,
                "angryCount": 2,
                "thankfulCount": 0,
                "careCount": 2,
                "likeCount": 681,
                "commentCount": 19
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 3,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 1,
                "sadCount": 0,
                "angryCount": 2,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 68,
                "commentCount": 2
            },
            "Neutral": {
                "count": 10,
                "viewCount": 34925,
                "favoriteCount": 0,
                "shareCount": 184,
                "loveCount": 35,
                "wowCount": 5,
                "hahaCount": 78,
                "sadCount": 7,
                "angryCount": 34,
                "thankfulCount": 0,
                "careCount": 4,
                "likeCount": 2288,
                "commentCount": 591
            }
        },
        "ერი": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            }
        },
        "ქართული ოცნება": {
            "Pole A": {
                "count": 7,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 225,
                "loveCount": 43,
                "wowCount": 15,
                "hahaCount": 161,
                "sadCount": 12,
                "angryCount": 154,
                "thankfulCount": 0,
                "careCount": 4,
                "likeCount": 3392,
                "commentCount": 619
            },
            "Pole B": {
                "count": 11,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 544,
                "loveCount": 1622,
                "wowCount": 3,
                "hahaCount": 112,
                "sadCount": 4,
                "angryCount": 24,
                "thankfulCount": 0,
                "careCount": 51,
                "likeCount": 9227,
                "commentCount": 2029
            },
            "Neutral": {
                "count": 11,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 654,
                "loveCount": 321,
                "wowCount": 18,
                "hahaCount": 376,
                "sadCount": 15,
                "angryCount": 253,
                "thankfulCount": 0,
                "careCount": 20,
                "likeCount": 5690,
                "commentCount": 1291
            }
        },
        "საქართველოსთვის": {
            "Pole A": {
                "count": 8,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 72,
                "loveCount": 13,
                "wowCount": 1,
                "hahaCount": 9,
                "sadCount": 0,
                "angryCount": 11,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 406,
                "commentCount": 24
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 7,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 223,
                "loveCount": 146,
                "wowCount": 13,
                "hahaCount": 241,
                "sadCount": 8,
                "angryCount": 152,
                "thankfulCount": 0,
                "careCount": 11,
                "likeCount": 2045,
                "commentCount": 284
            }
        },
        "ერთიანი ნაციონალური მოძრაობა": {
            "Pole A": {
                "count": 84,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 7457,
                "loveCount": 8712,
                "wowCount": 745,
                "hahaCount": 7159,
                "sadCount": 2767,
                "angryCount": 1787,
                "thankfulCount": 0,
                "careCount": 624,
                "likeCount": 59064,
                "commentCount": 21427
            },
            "Pole B": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 147,
                "loveCount": 157,
                "wowCount": 0,
                "hahaCount": 10,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 10,
                "likeCount": 1015,
                "commentCount": 255
            },
            "Neutral": {
                "count": 92,
                "viewCount": 1165,
                "favoriteCount": 0,
                "shareCount": 7891,
                "loveCount": 9591,
                "wowCount": 307,
                "hahaCount": 10311,
                "sadCount": 344,
                "angryCount": 1160,
                "thankfulCount": 0,
                "careCount": 658,
                "likeCount": 63191,
                "commentCount": 21234
            }
        },
        "ხალხისთვის": {
            "Pole A": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 18,
                "loveCount": 13,
                "wowCount": 0,
                "hahaCount": 3,
                "sadCount": 5,
                "angryCount": 4,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 812,
                "commentCount": 66
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 3,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 248,
                "loveCount": 447,
                "wowCount": 11,
                "hahaCount": 81,
                "sadCount": 7,
                "angryCount": 26,
                "thankfulCount": 0,
                "careCount": 23,
                "likeCount": 3782,
                "commentCount": 631
            }
        },
        "სტრატეგია აღმაშენებელი": {
            "Pole A": {
                "count": 7,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 63,
                "loveCount": 43,
                "wowCount": 5,
                "hahaCount": 236,
                "sadCount": 6,
                "angryCount": 16,
                "thankfulCount": 0,
                "careCount": 4,
                "likeCount": 630,
                "commentCount": 116
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 12,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 186,
                "loveCount": 120,
                "wowCount": 24,
                "hahaCount": 83,
                "sadCount": 6,
                "angryCount": 30,
                "thankfulCount": 0,
                "careCount": 6,
                "likeCount": 956,
                "commentCount": 206
            }
        },
        "მოქალაქეები": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            }
        },
        "კონსერვატიული მოძრაობა": {
            "Pole A": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 10,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 60,
                "loveCount": 42,
                "wowCount": 0,
                "hahaCount": 5,
                "sadCount": 3,
                "angryCount": 2,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 466,
                "commentCount": 49
            }
        },
        "ხალხის ძალა": {
            "Pole A": {
                "count": 11,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 337,
                "loveCount": 277,
                "wowCount": 4,
                "hahaCount": 20,
                "sadCount": 6,
                "angryCount": 1,
                "thankfulCount": 0,
                "careCount": 8,
                "likeCount": 2787,
                "commentCount": 542
            },
            "Pole B": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 10,
                "loveCount": 4,
                "wowCount": 0,
                "hahaCount": 4,
                "sadCount": 0,
                "angryCount": 3,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 182,
                "commentCount": 7
            },
            "Neutral": {
                "count": 34,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 452,
                "loveCount": 87,
                "wowCount": 25,
                "hahaCount": 46,
                "sadCount": 9,
                "angryCount": 11,
                "thankfulCount": 0,
                "careCount": 4,
                "likeCount": 3707,
                "commentCount": 254
            }
        },
        "ევროპული საქართველო - მოძრაობა თავისუფლებისთვის": {
            "Pole A": {
                "count": 14,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 452,
                "loveCount": 160,
                "wowCount": 13,
                "hahaCount": 357,
                "sadCount": 16,
                "angryCount": 269,
                "thankfulCount": 0,
                "careCount": 12,
                "likeCount": 4296,
                "commentCount": 663
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 20,
                "loveCount": 38,
                "wowCount": 0,
                "hahaCount": 1,
                "sadCount": 0,
                "angryCount": 2,
                "thankfulCount": 0,
                "careCount": 2,
                "likeCount": 392,
                "commentCount": 48
            }
        },
        "პატრიოტთა ალიანსი": {
            "Pole A": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 12,
                "commentCount": 1
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 8,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 73,
                "loveCount": 29,
                "wowCount": 3,
                "hahaCount": 14,
                "sadCount": 4,
                "angryCount": 12,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 434,
                "commentCount": 72
            }
        },
        "ლელო": {
            "Pole A": {
                "count": 9,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 134,
                "loveCount": 111,
                "wowCount": 5,
                "hahaCount": 21,
                "sadCount": 1,
                "angryCount": 51,
                "thankfulCount": 0,
                "careCount": 6,
                "likeCount": 1821,
                "commentCount": 308
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 6,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 13,
                "loveCount": 9,
                "wowCount": 0,
                "hahaCount": 17,
                "sadCount": 1,
                "angryCount": 2,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 158,
                "commentCount": 25
            }
        },
        "გირჩი - მეტი თავისუფლება": {
            "Pole A": {
                "count": 19,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1403,
                "loveCount": 760,
                "wowCount": 16,
                "hahaCount": 509,
                "sadCount": 30,
                "angryCount": 95,
                "thankfulCount": 0,
                "careCount": 44,
                "likeCount": 14762,
                "commentCount": 1287
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 1,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 2,
                "commentCount": 0
            },
            "Neutral": {
                "count": 17,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 651,
                "loveCount": 300,
                "wowCount": 4,
                "hahaCount": 59,
                "sadCount": 23,
                "angryCount": 25,
                "thankfulCount": 0,
                "careCount": 25,
                "likeCount": 9809,
                "commentCount": 673
            }
        },
        "ლეიბორისტული პარტია": {
            "Pole A": {
                "count": 27,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 809,
                "loveCount": 1309,
                "wowCount": 92,
                "hahaCount": 235,
                "sadCount": 432,
                "angryCount": 109,
                "thankfulCount": 0,
                "careCount": 68,
                "likeCount": 13730,
                "commentCount": 1941
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 9,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 315,
                "loveCount": 75,
                "wowCount": 51,
                "hahaCount": 369,
                "sadCount": 298,
                "angryCount": 53,
                "thankfulCount": 0,
                "careCount": 13,
                "likeCount": 3834,
                "commentCount": 1090
            }
        },
        "დროა": {
            "Pole A": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 1,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 15,
                "commentCount": 0
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 8,
                "loveCount": 10,
                "wowCount": 0,
                "hahaCount": 8,
                "sadCount": 0,
                "angryCount": 1,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 85,
                "commentCount": 6
            }
        }
    },
    "west_vv": {
        "გირჩი": {
            "Pole A": {
                "count": 26,
                "viewCount": 56463,
                "favoriteCount": 0,
                "shareCount": 2111,
                "loveCount": 987,
                "wowCount": 15,
                "hahaCount": 31,
                "sadCount": 3213,
                "angryCount": 23,
                "thankfulCount": 0,
                "careCount": 64,
                "likeCount": 5646,
                "commentCount": 1500
            },
            "Pole B": {
                "count": 5,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 96,
                "loveCount": 88,
                "wowCount": 0,
                "hahaCount": 15,
                "sadCount": 2,
                "angryCount": 8,
                "thankfulCount": 0,
                "careCount": 3,
                "likeCount": 1639,
                "commentCount": 137
            },
            "Neutral": {
                "count": 141,
                "viewCount": 265244,
                "favoriteCount": 0,
                "shareCount": 1860,
                "loveCount": 783,
                "wowCount": 68,
                "hahaCount": 697,
                "sadCount": 46,
                "angryCount": 192,
                "thankfulCount": 0,
                "careCount": 47,
                "likeCount": 22750,
                "commentCount": 4618
            }
        },
        "ერი": {
            "Pole A": {
                "count": 7,
                "viewCount": 4839,
                "favoriteCount": 0,
                "shareCount": 48,
                "loveCount": 137,
                "wowCount": 0,
                "hahaCount": 1,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 4,
                "likeCount": 534,
                "commentCount": 31
            },
            "Pole B": {
                "count": 2,
                "viewCount": 1227,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 62,
                "commentCount": 0
            },
            "Neutral": {
                "count": 85,
                "viewCount": 27275,
                "favoriteCount": 0,
                "shareCount": 395,
                "loveCount": 296,
                "wowCount": 3,
                "hahaCount": 2,
                "sadCount": 2,
                "angryCount": 10,
                "thankfulCount": 0,
                "careCount": 9,
                "likeCount": 2984,
                "commentCount": 183
            }
        },
        "ქართული ოცნება": {
            "Pole A": {
                "count": 645,
                "viewCount": 456,
                "favoriteCount": 0,
                "shareCount": 16144,
                "loveCount": 26816,
                "wowCount": 336,
                "hahaCount": 17907,
                "sadCount": 1677,
                "angryCount": 10634,
                "thankfulCount": 0,
                "careCount": 1173,
                "likeCount": 243711,
                "commentCount": 43244
            },
            "Pole B": {
                "count": 16,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1397,
                "loveCount": 149,
                "wowCount": 17,
                "hahaCount": 303,
                "sadCount": 14,
                "angryCount": 184,
                "thankfulCount": 0,
                "careCount": 13,
                "likeCount": 8090,
                "commentCount": 1257
            },
            "Neutral": {
                "count": 290,
                "viewCount": 574,
                "favoriteCount": 0,
                "shareCount": 10062,
                "loveCount": 8711,
                "wowCount": 321,
                "hahaCount": 5941,
                "sadCount": 4255,
                "angryCount": 6681,
                "thankfulCount": 0,
                "careCount": 408,
                "likeCount": 123053,
                "commentCount": 25193
            }
        },
        "საქართველოსთვის": {
            "Pole A": {
                "count": 62,
                "viewCount": 31,
                "favoriteCount": 0,
                "shareCount": 1245,
                "loveCount": 2356,
                "wowCount": 61,
                "hahaCount": 772,
                "sadCount": 78,
                "angryCount": 350,
                "thankfulCount": 0,
                "careCount": 134,
                "likeCount": 17963,
                "commentCount": 1612
            },
            "Pole B": {
                "count": 19,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 2087,
                "loveCount": 2139,
                "wowCount": 29,
                "hahaCount": 214,
                "sadCount": 14,
                "angryCount": 105,
                "thankfulCount": 0,
                "careCount": 82,
                "likeCount": 15402,
                "commentCount": 1343
            },
            "Neutral": {
                "count": 75,
                "viewCount": 55,
                "favoriteCount": 0,
                "shareCount": 1660,
                "loveCount": 1463,
                "wowCount": 94,
                "hahaCount": 1743,
                "sadCount": 204,
                "angryCount": 502,
                "thankfulCount": 0,
                "careCount": 72,
                "likeCount": 17571,
                "commentCount": 2116
            }
        },
        "ერთიანი ნაციონალური მოძრაობა": {
            "Pole A": {
                "count": 223,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 18607,
                "loveCount": 33656,
                "wowCount": 497,
                "hahaCount": 16077,
                "sadCount": 8213,
                "angryCount": 2324,
                "thankfulCount": 0,
                "careCount": 2252,
                "likeCount": 183544,
                "commentCount": 50676
            },
            "Pole B": {
                "count": 39,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 2425,
                "loveCount": 1982,
                "wowCount": 318,
                "hahaCount": 2992,
                "sadCount": 2097,
                "angryCount": 1011,
                "thankfulCount": 0,
                "careCount": 158,
                "likeCount": 15236,
                "commentCount": 5617
            },
            "Neutral": {
                "count": 313,
                "viewCount": 1485,
                "favoriteCount": 0,
                "shareCount": 17427,
                "loveCount": 20930,
                "wowCount": 1208,
                "hahaCount": 21410,
                "sadCount": 2870,
                "angryCount": 4764,
                "thankfulCount": 0,
                "careCount": 1557,
                "likeCount": 149747,
                "commentCount": 49519
            }
        },
        "ხალხისთვის": {
            "Pole A": {
                "count": 10,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1162,
                "loveCount": 2452,
                "wowCount": 71,
                "hahaCount": 466,
                "sadCount": 21,
                "angryCount": 152,
                "thankfulCount": 0,
                "careCount": 139,
                "likeCount": 15453,
                "commentCount": 2054
            },
            "Pole B": {
                "count": 2,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 156,
                "loveCount": 18,
                "wowCount": 11,
                "hahaCount": 12,
                "sadCount": 6,
                "angryCount": 120,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 1197,
                "commentCount": 149
            },
            "Neutral": {
                "count": 32,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1753,
                "loveCount": 1904,
                "wowCount": 176,
                "hahaCount": 705,
                "sadCount": 417,
                "angryCount": 920,
                "thankfulCount": 0,
                "careCount": 90,
                "likeCount": 24560,
                "commentCount": 4306
            }
        },
        "სტრატეგია აღმაშენებელი": {
            "Pole A": {
                "count": 223,
                "viewCount": 100,
                "favoriteCount": 0,
                "shareCount": 15688,
                "loveCount": 22494,
                "wowCount": 457,
                "hahaCount": 10895,
                "sadCount": 8157,
                "angryCount": 2313,
                "thankfulCount": 0,
                "careCount": 2359,
                "likeCount": 190386,
                "commentCount": 39612
            },
            "Pole B": {
                "count": 26,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 538,
                "loveCount": 749,
                "wowCount": 75,
                "hahaCount": 834,
                "sadCount": 62,
                "angryCount": 950,
                "thankfulCount": 0,
                "careCount": 74,
                "likeCount": 6534,
                "commentCount": 1969
            },
            "Neutral": {
                "count": 176,
                "viewCount": 84,
                "favoriteCount": 0,
                "shareCount": 7153,
                "loveCount": 9033,
                "wowCount": 757,
                "hahaCount": 5435,
                "sadCount": 614,
                "angryCount": 3209,
                "thankfulCount": 0,
                "careCount": 810,
                "likeCount": 78827,
                "commentCount": 15137
            }
        },
        "მოქალაქეები": {
            "Pole A": {
                "count": 32,
                "viewCount": 31,
                "favoriteCount": 0,
                "shareCount": 219,
                "loveCount": 362,
                "wowCount": 29,
                "hahaCount": 188,
                "sadCount": 15,
                "angryCount": 134,
                "thankfulCount": 0,
                "careCount": 13,
                "likeCount": 8584,
                "commentCount": 1380
            },
            "Pole B": {
                "count": 0,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 0,
                "loveCount": 0,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 0,
                "commentCount": 0
            },
            "Neutral": {
                "count": 42,
                "viewCount": 22,
                "favoriteCount": 0,
                "shareCount": 2828,
                "loveCount": 1916,
                "wowCount": 72,
                "hahaCount": 333,
                "sadCount": 91,
                "angryCount": 163,
                "thankfulCount": 0,
                "careCount": 101,
                "likeCount": 25249,
                "commentCount": 3409
            }
        },
        "კონსერვატიული მოძრაობა": {
            "Pole A": {
                "count": 71,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 738,
                "loveCount": 814,
                "wowCount": 11,
                "hahaCount": 312,
                "sadCount": 10,
                "angryCount": 55,
                "thankfulCount": 0,
                "careCount": 42,
                "likeCount": 5449,
                "commentCount": 1080
            },
            "Pole B": {
                "count": 84,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 5086,
                "loveCount": 737,
                "wowCount": 130,
                "hahaCount": 662,
                "sadCount": 173,
                "angryCount": 598,
                "thankfulCount": 0,
                "careCount": 49,
                "likeCount": 13542,
                "commentCount": 4014
            },
            "Neutral": {
                "count": 820,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 25820,
                "loveCount": 3065,
                "wowCount": 1074,
                "hahaCount": 5368,
                "sadCount": 985,
                "angryCount": 13562,
                "thankfulCount": 0,
                "careCount": 262,
                "likeCount": 61422,
                "commentCount": 15160
            }
        },
        "ხალხის ძალა": {
            "Pole A": {
                "count": 136,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1888,
                "loveCount": 1211,
                "wowCount": 19,
                "hahaCount": 701,
                "sadCount": 230,
                "angryCount": 848,
                "thankfulCount": 0,
                "careCount": 51,
                "likeCount": 19398,
                "commentCount": 2442
            },
            "Pole B": {
                "count": 86,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1710,
                "loveCount": 435,
                "wowCount": 69,
                "hahaCount": 675,
                "sadCount": 46,
                "angryCount": 316,
                "thankfulCount": 0,
                "careCount": 13,
                "likeCount": 14304,
                "commentCount": 2016
            },
            "Neutral": {
                "count": 381,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 8514,
                "loveCount": 4112,
                "wowCount": 343,
                "hahaCount": 1964,
                "sadCount": 207,
                "angryCount": 2130,
                "thankfulCount": 0,
                "careCount": 192,
                "likeCount": 78188,
                "commentCount": 12302
            }
        },
        "ევროპული საქართველო - მოძრაობა თავისუფლებისთვის": {
            "Pole A": {
                "count": 22,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 634,
                "loveCount": 2226,
                "wowCount": 27,
                "hahaCount": 816,
                "sadCount": 25,
                "angryCount": 244,
                "thankfulCount": 0,
                "careCount": 109,
                "likeCount": 17035,
                "commentCount": 3132
            },
            "Pole B": {
                "count": 9,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 173,
                "loveCount": 34,
                "wowCount": 11,
                "hahaCount": 326,
                "sadCount": 7,
                "angryCount": 248,
                "thankfulCount": 0,
                "careCount": 4,
                "likeCount": 1585,
                "commentCount": 329
            },
            "Neutral": {
                "count": 39,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 900,
                "loveCount": 546,
                "wowCount": 22,
                "hahaCount": 369,
                "sadCount": 125,
                "angryCount": 154,
                "thankfulCount": 0,
                "careCount": 41,
                "likeCount": 7511,
                "commentCount": 1506
            }
        },
        "პატრიოტთა ალიანსი": {
            "Pole A": {
                "count": 18,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 62,
                "loveCount": 34,
                "wowCount": 1,
                "hahaCount": 18,
                "sadCount": 6,
                "angryCount": 17,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 614,
                "commentCount": 70
            },
            "Pole B": {
                "count": 8,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 117,
                "loveCount": 14,
                "wowCount": 5,
                "hahaCount": 42,
                "sadCount": 2,
                "angryCount": 31,
                "thankfulCount": 0,
                "careCount": 1,
                "likeCount": 489,
                "commentCount": 130
            },
            "Neutral": {
                "count": 36,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 234,
                "loveCount": 82,
                "wowCount": 7,
                "hahaCount": 86,
                "sadCount": 3,
                "angryCount": 65,
                "thankfulCount": 0,
                "careCount": 2,
                "likeCount": 1882,
                "commentCount": 310
            }
        },
        "ლელო": {
            "Pole A": {
                "count": 127,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 2826,
                "loveCount": 6929,
                "wowCount": 100,
                "hahaCount": 1485,
                "sadCount": 1653,
                "angryCount": 497,
                "thankfulCount": 0,
                "careCount": 422,
                "likeCount": 45420,
                "commentCount": 5240
            },
            "Pole B": {
                "count": 6,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 275,
                "loveCount": 79,
                "wowCount": 2,
                "hahaCount": 73,
                "sadCount": 2,
                "angryCount": 22,
                "thankfulCount": 0,
                "careCount": 11,
                "likeCount": 3124,
                "commentCount": 307
            },
            "Neutral": {
                "count": 128,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 2960,
                "loveCount": 3586,
                "wowCount": 122,
                "hahaCount": 1577,
                "sadCount": 515,
                "angryCount": 724,
                "thankfulCount": 0,
                "careCount": 279,
                "likeCount": 35714,
                "commentCount": 4064
            }
        },
        "გირჩი - მეტი თავისუფლება": {
            "Pole A": {
                "count": 63,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 2458,
                "loveCount": 5461,
                "wowCount": 35,
                "hahaCount": 463,
                "sadCount": 20,
                "angryCount": 121,
                "thankfulCount": 0,
                "careCount": 280,
                "likeCount": 28669,
                "commentCount": 3233
            },
            "Pole B": {
                "count": 11,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1639,
                "loveCount": 1443,
                "wowCount": 23,
                "hahaCount": 470,
                "sadCount": 34,
                "angryCount": 150,
                "thankfulCount": 0,
                "careCount": 60,
                "likeCount": 15561,
                "commentCount": 2403
            },
            "Neutral": {
                "count": 113,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 4771,
                "loveCount": 6334,
                "wowCount": 113,
                "hahaCount": 1027,
                "sadCount": 595,
                "angryCount": 5587,
                "thankfulCount": 0,
                "careCount": 301,
                "likeCount": 43545,
                "commentCount": 4664
            }
        },
        "ლეიბორისტული პარტია": {
            "Pole A": {
                "count": 10,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 586,
                "loveCount": 331,
                "wowCount": 7,
                "hahaCount": 72,
                "sadCount": 1,
                "angryCount": 20,
                "thankfulCount": 0,
                "careCount": 16,
                "likeCount": 4149,
                "commentCount": 452
            },
            "Pole B": {
                "count": 7,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 109,
                "loveCount": 38,
                "wowCount": 33,
                "hahaCount": 60,
                "sadCount": 14,
                "angryCount": 17,
                "thankfulCount": 0,
                "careCount": 3,
                "likeCount": 1851,
                "commentCount": 259
            },
            "Neutral": {
                "count": 38,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1134,
                "loveCount": 470,
                "wowCount": 125,
                "hahaCount": 1452,
                "sadCount": 619,
                "angryCount": 178,
                "thankfulCount": 0,
                "careCount": 52,
                "likeCount": 13047,
                "commentCount": 2471
            }
        },
        "დროა": {
            "Pole A": {
                "count": 52,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1328,
                "loveCount": 3412,
                "wowCount": 43,
                "hahaCount": 1891,
                "sadCount": 32,
                "angryCount": 352,
                "thankfulCount": 0,
                "careCount": 248,
                "likeCount": 18275,
                "commentCount": 4357
            },
            "Pole B": {
                "count": 1,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 4,
                "loveCount": 1,
                "wowCount": 0,
                "hahaCount": 0,
                "sadCount": 0,
                "angryCount": 0,
                "thankfulCount": 0,
                "careCount": 0,
                "likeCount": 41,
                "commentCount": 1
            },
            "Neutral": {
                "count": 46,
                "viewCount": 0,
                "favoriteCount": 0,
                "shareCount": 1023,
                "loveCount": 1931,
                "wowCount": 73,
                "hahaCount": 848,
                "sadCount": 114,
                "angryCount": 1977,
                "thankfulCount": 0,
                "careCount": 194,
                "likeCount": 10846,
                "commentCount": 2111
            }
        }
    }
}